"""Predeclare every standby batch, then bind actual UI actions exactly once.

UI action IDs are generated by the real TUI, never reserved by this tool.
This evidence supplies the fixed expected set for a later run terminal. It
does not send input, launch natives, stop owners, or certify run completion.
"""
from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path
import stat
import uuid

import cmux_codex_watch as core
import ccc_workspace_batch as batch
from ccc_batch_timing import stamp
from ccc_native_standby import COUNT, identifier, write_once
from ccc_standby_settlement import read_settlement
from ccc_standby_timing import _clock, _elapsed, _read, _sha


def directory_identity(directory):
    directory = Path(directory)
    info = directory.lstat()
    if (not directory.is_absolute() or directory.resolve(strict=True) != directory
            or not stat.S_ISDIR(info.st_mode) or info.st_uid != os.geteuid()
            or stat.S_IMODE(info.st_mode) & 0o077):
        raise ValueError('private canonical run evidence directory required')
    return info.st_dev, info.st_ino, info.st_mode, info.st_uid


def validate_plan(plan):
    if (not isinstance(plan, dict) or type(plan.get('version')) is not int
            or plan['version'] != 1 or plan.get('kind') != 'standby_run_plan'):
        raise ValueError('original standby run plan required')
    identifier(plan['run_id'])
    _clock(plan['declared'], plan['boot_id'])
    batches = plan.get('batches')
    if not isinstance(batches, list) or not 1 <= len(batches) <= 100:
        raise ValueError('declare all 1..100 batches before any UI action')
    seen, topology, spellings = set(), {}, {}
    for row in batches:
        if not isinstance(row, dict) or set(row) != {'batch_id', 'workspace_id', 'mode', 'slots'}:
            raise ValueError('invalid planned batch')
        key = identifier(row['batch_id'])
        workspace = identifier(row['workspace_id'])
        if (key in seen or row['mode'] not in ('b', 'N')
                or type(row['slots']) is not int or row['slots'] != COUNT):
            raise ValueError('duplicate batch or invalid original standby scope')
        # Preserve controller spelling, but do not allow two spellings of one
        # UUID to masquerade as distinct workspaces in the declared topology.
        if workspace in spellings and spellings[workspace] != row['workspace_id']:
            raise ValueError('workspace UUID spelling differs within run')
        spellings[workspace] = row['workspace_id']
        seen.add(key)
        topology[row['workspace_id']] = topology.get(row['workspace_id'], 0) + COUNT
    if (type(plan.get('planned_sessions')) is not int
            or plan['planned_sessions'] != COUNT * len(batches)
            or plan.get('workspace_slots') != topology):
        raise ValueError('run topology differs from complete declared batch set')
    return plan


def declare(directory, batches, *, clock=stamp):
    directory = Path(directory)
    identity = directory_identity(directory)
    now = clock()
    topology = {}
    if not isinstance(batches, list) or not 1 <= len(batches) <= 100:
        raise ValueError('declare all 1..100 batches before any UI action')
    for row in batches:
        if (not isinstance(row, dict)
                or not isinstance(row.get('workspace_id'), str)
                or type(row.get('slots')) is not int):
            raise ValueError('invalid planned batch')
        topology[row['workspace_id']] = topology.get(row['workspace_id'], 0) + row['slots']
    plan = validate_plan({'version': 1, 'kind': 'standby_run_plan',
        'run_id': str(uuid.uuid4()), 'boot_id': now['boot_id'], 'declared': now,
        'batches': copy.deepcopy(batches), 'planned_sessions': COUNT * len(batches),
        'workspace_slots': topology})
    if directory_identity(directory) != identity:
        raise ValueError('run directory changed')
    write_once(directory/'run-plan.json', plan)
    return plan


class RunManifest:
    def __init__(self, directory):
        self.directory = Path(directory)
        self.identity = directory_identity(self.directory)
        self.path = self.directory/'run-plan.json'
        self.plan, self.raw = _read(self.path)
        validate_plan(self.plan)
        self.sha256 = _sha(self.raw)

    def current(self):
        if (directory_identity(self.directory) != self.identity
                or _read(self.path)[1] != self.raw):
            raise ValueError('original run plan changed')

    def _attempt(self, expected):
        from ccc_standby_runner import Invocation
        path = self.directory / f"attempt-{identifier(expected['batch_id'])}.json"
        value, raw = _read(path)
        if (value.get('kind') != 'standby_run_attempt' or value.get('version') != 1
                or value.get('run_id') != self.plan['run_id']
                or value.get('plan_sha256') != self.sha256
                or value.get('batch_id') != identifier(expected['batch_id'])
                or any(value.get(k) != expected[k] for k in ('workspace_id', 'mode', 'slots'))):
            raise ValueError('attempt differs from declared batch')
        invocation = Invocation(value['invocation_path'], value['invocation_sha256'])
        if (invocation.value['invocation_id'] != value['invocation_id']
                or any(invocation.value[k] != value[k] for k in ('workspace_id', 'mode'))
                or list(directory_identity(value['runner_directory'])) != value['runner_identity']):
            raise ValueError('original attempt identity changed')
        _elapsed(self.plan['declared'], value['registered'], self.plan['boot_id'])
        return path, value, raw, invocation

    def register_attempt(self, batch_id, invocation_path, invocation_sha256,
                         runner_directory, *, clock=stamp):
        """Bind a batch before its runner starts, including pre-admission failures.

        Registration neither starts a runner nor grants native/UI authorization.
        It preserves the declared scope when no activation/settlement is produced.
        """
        from ccc_standby_runner import Invocation
        batch_id = identifier(batch_id)
        runner_directory = Path(runner_directory)
        with core.FileLock(self.directory/'run-bind.lock', purpose='register run attempt'):
            self.current()
            expected = next((r for r in self.plan['batches']
                             if identifier(r['batch_id']) == batch_id), None)
            if expected is None:
                raise ValueError('batch was not declared')
            invocation = Invocation(invocation_path, invocation_sha256)
            if any(invocation.value[k] != expected[k] for k in ('workspace_id', 'mode')):
                raise ValueError('invocation differs from declared batch')
            identity = directory_identity(runner_directory)
            target = self.directory / f'attempt-{batch_id}.json'
            record = {'version': 1, 'kind': 'standby_run_attempt',
                'run_id': self.plan['run_id'], 'plan_sha256': self.sha256,
                'batch_id': batch_id, **{k: expected[k] for k in ('workspace_id', 'mode', 'slots')},
                'invocation_id': invocation.value['invocation_id'],
                'invocation_path': str(invocation.path), 'invocation_sha256': invocation.sha256,
                'runner_directory': str(runner_directory), 'runner_identity': list(identity)}
            pinned = []
            existing = None
            for row in self.plan['batches']:
                path = self.directory / f"attempt-{identifier(row['batch_id'])}.json"
                if not os.path.lexists(path):
                    continue
                path, value, raw, old_invocation = self._attempt(row)
                pinned.append((path, raw, old_invocation))
                if path == target:
                    if {k: v for k, v in value.items() if k != 'registered'} != record:
                        raise ValueError('attempt already bound to another invocation')
                    existing = value
                elif (identifier(value['invocation_id']) == identifier(record['invocation_id'])
                      or value['runner_identity'][:2] == record['runner_identity'][:2]):
                    raise ValueError('invocation or runner directory already consumed')
            now = clock()
            _elapsed(self.plan['declared'], now, self.plan['boot_id'])
            self.current()
            invocation.current()
            for path, raw, original in pinned:
                original.current()
                if _read(path)[1] != raw:
                    raise ValueError('attempt changed during registration')
            if directory_identity(runner_directory) != identity:
                raise ValueError('runner directory changed')
            if existing is not None:
                _elapsed(existing['registered'], now, self.plan['boot_id'])
                return copy.deepcopy(existing)
            if (any(runner_directory.glob('runner-*.json'))
                    or os.path.lexists(self.directory / f'batch-{batch_id}.json')):
                raise ValueError('attempt must be registered before runner or activation')
            record['registered'] = now
            write_once(target, record)
            return copy.deepcopy(record)

    def attempts(self):
        """Read the complete declared attempt set, never omit failed admissions."""
        with core.FileLock(self.directory/'run-bind.lock', purpose='read run attempts'):
            self.current()
            paths = {self.directory / f"attempt-{identifier(r['batch_id'])}.json"
                     for r in self.plan['batches']}
            if set(self.directory.glob('attempt-*.json')) != paths:
                raise ValueError('complete declared attempt set required')
            pinned = [self._attempt(row) for row in self.plan['batches']]
            invocations = [identifier(value['invocation_id']) for _, value, _, _ in pinned]
            directories = [tuple(value['runner_identity'][:2]) for _, value, _, _ in pinned]
            if len(set(invocations)) != len(pinned) or len(set(directories)) != len(pinned):
                raise ValueError('duplicate original run attempt')
            for path, value, raw, invocation in pinned:
                invocation.current()
                if (_read(path)[1] != raw or
                        list(directory_identity(value['runner_directory'])) != value['runner_identity']):
                    raise ValueError('attempt changed during resolution')
            self.current()
            if set(self.directory.glob('attempt-*.json')) != paths:
                raise ValueError('attempt set changed during resolution')
            return [{'attempt_path': str(p), 'attempt_sha256': _sha(raw), 'attempt': value}
                    for p, value, raw, _ in pinned]

    def _binding_record(self, path, expected):
        value, raw = _read(path)
        if (value.get('version') != 1 or value.get('kind') != 'standby_run_batch_binding'
                or value.get('run_id') != self.plan['run_id']
                or value.get('plan_sha256') != self.sha256
                or value.get('batch_id') != identifier(expected['batch_id'])
                or value.get('boot_id') != self.plan['boot_id']
                or any(value.get(k) != expected[k] for k in ('workspace_id', 'mode', 'slots'))):
            raise ValueError('existing binding differs from original run plan')
        for key in ('job_id', 'action_id', 'cohort_id'):
            identifier(value[key])
        _elapsed(self.plan['declared'], value['bound'], self.plan['boot_id'])
        return value, raw

    def _original_binding(self, value):
        """Reopen originals; a saved binding alone is never sufficient."""
        config = Path(value['config_path'])
        if not config.is_absolute() or config.resolve(strict=True) != config:
            raise ValueError('original canonical config path required')
        jobpath = batch.job_path(config, value['job_id'])
        ui_path = jobpath.parent/'standby'/'activation-ui.json'
        if value['job_path'] != str(jobpath) or value['activation_ui_path'] != str(ui_path):
            raise ValueError('binding original paths differ')
        saved, sha = read_settlement(config, value['job_id'])
        ui, raw = _read(ui_path)
        if (sha != value['settlement_sha256']
                or _sha(raw) != value['activation_ui_sha256']
                or saved['activation_ui_sha256'] != _sha(raw)
                or any(saved[k] != value[k] for k in
                       ('job_id', 'action_id', 'cohort_id', 'workspace_id', 'mode', 'boot_id'))
                or ui['action_id'] != value['action_id']):
            raise ValueError('bound original evidence changed')
        origin = ui['origin']['events'][0]
        if origin['phase'] != 'input_read':
            raise ValueError('original UI input timestamp required')
        _elapsed(self.plan['declared'], origin, self.plan['boot_id'])
        _elapsed(ui['event'], value['bound'], self.plan['boot_id'])
        return saved, sha, raw

    def resolve(self, *, clock=stamp):
        """Freeze the complete actual action set for later terminal collection.

        No subset is accepted. This revalidates original submission evidence,
        not live task completion, simultaneous liveness or owner cleanup.
        """
        with core.FileLock(self.directory/'run-bind.lock', purpose='resolve all run bindings'):
            self.current()
            rows, originals, pinned = [], [], []
            seen = {key: set() for key in ('job_id', 'action_id', 'cohort_id')}
            expected_paths = {self.directory/f"batch-{identifier(row['batch_id'])}.json"
                              for row in self.plan['batches']}
            if set(self.directory.glob('batch-*.json')) != expected_paths:
                raise ValueError('complete declared batch binding set required')
            for expected in self.plan['batches']:
                path = self.directory/f"batch-{identifier(expected['batch_id'])}.json"
                value, raw = self._binding_record(path, expected)
                for key, values in seen.items():
                    canonical = identifier(value[key])
                    if canonical in values:
                        raise ValueError('duplicate original job/action/cohort in run')
                    values.add(canonical)
                originals.append(self._original_binding(value))
                pinned.append((path, raw, value))
                rows.append({'binding_path': str(path), 'binding_sha256': _sha(raw),
                             'binding': value})
            for (_, _, value), original in zip(pinned, originals):
                if self._original_binding(value) != original:
                    raise ValueError('original batch evidence changed during resolution')
            self.current()
            if (set(self.directory.glob('batch-*.json')) != expected_paths
                    or any(_read(path)[1] != raw for path, raw, _ in pinned)):
                raise ValueError('batch bindings changed during resolution')
            now = clock()
            for _, _, value in pinned:
                _elapsed(value['bound'], now, self.plan['boot_id'])
            record = {'version': 1, 'kind': 'standby_run_bindings',
                'run_id': self.plan['run_id'], 'boot_id': self.plan['boot_id'],
                'plan_sha256': self.sha256, 'planned_sessions': self.plan['planned_sessions'],
                'workspace_slots': self.plan['workspace_slots'], 'batches': rows,
                'job_terminal': False, 'run_terminal': False}
            target = self.directory/'run-bindings.json'
            if os.path.lexists(target):
                saved, _ = _read(target)
                if {k: v for k, v in saved.items() if k != 'resolved'} != record:
                    raise ValueError('resolved complete run bindings changed')
                _elapsed(self.plan['declared'], saved['resolved'], self.plan['boot_id'])
                for _, _, value in pinned:
                    _elapsed(value['bound'], saved['resolved'], self.plan['boot_id'])
                _elapsed(saved['resolved'], now, self.plan['boot_id'])
                return copy.deepcopy(saved)
            record['resolved'] = now
            write_once(target, record)
            return copy.deepcopy(record)

    def bind(self, batch_id, config_path, job_id, *, clock=stamp):
        """Bind validated original settlement/UI bytes, not supplied summaries.

        This is post-activation bookkeeping. The declaration itself must
        precede input_read, and it can never grant activation authorization.
        """
        batch_id, job_id = identifier(batch_id), identifier(job_id)
        config_path = Path(config_path).resolve(strict=True)
        with core.FileLock(self.directory/'run-bind.lock', purpose='run evidence binding'):
            self.current()
            expected = next((r for r in self.plan['batches']
                             if identifier(r['batch_id']) == batch_id), None)
            if expected is None:
                raise ValueError('batch was not declared')
            saved, settlement_sha = read_settlement(config_path, job_id)
            jobpath = batch.job_path(config_path, job_id)
            ui_path = jobpath.parent/'standby'/'activation-ui.json'
            ui, ui_raw = _read(ui_path)
            if (saved['job_id'] != job_id or saved['boot_id'] != self.plan['boot_id']
                    or any(saved[k] != expected[k] for k in ('workspace_id', 'mode'))
                    or _sha(ui_raw) != saved['activation_ui_sha256']
                    or ui['action_id'] != saved['action_id']):
                raise ValueError('original UI/settlement differs from planned batch')
            origin = ui['origin']['events'][0]
            if origin['phase'] != 'input_read':
                raise ValueError('original UI input timestamp required')
            _elapsed(self.plan['declared'], origin, self.plan['boot_id'])
            now = clock()
            _elapsed(ui['event'], now, self.plan['boot_id'])
            target = self.directory/f'batch-{batch_id}.json'
            binding = {'version': 1, 'kind': 'standby_run_batch_binding',
                'run_id': self.plan['run_id'], 'plan_sha256': self.sha256,
                'batch_id': batch_id, 'slots': COUNT, 'config_path': str(config_path),
                'job_path': str(jobpath), 'settlement_sha256': settlement_sha,
                'activation_ui_path': str(ui_path), 'activation_ui_sha256': _sha(ui_raw),
                **{k: saved[k] for k in ('job_id', 'action_id', 'cohort_id',
                                       'workspace_id', 'mode', 'boot_id')}}
            prior = {}
            for row in self.plan['batches']:
                other_path = self.directory/f"batch-{identifier(row['batch_id'])}.json"
                if os.path.lexists(other_path):
                    other, other_raw = self._binding_record(other_path, row)
                    prior[other_path] = other_raw
                    if other_path == target:
                        if {k: v for k, v in other.items() if k != 'bound'} != binding:
                            raise ValueError('batch already bound to different original evidence')
                        # An existing binding is not rewritten or retimestamped.
                        binding = other
                    elif any(other.get(k) == binding[k] for k in ('job_id', 'action_id', 'cohort_id')):
                        raise ValueError('original job/action/cohort already consumed by another batch')
            if (read_settlement(config_path, job_id) != (saved, settlement_sha)
                    or _read(ui_path)[1] != ui_raw):
                raise ValueError('original evidence changed before binding')
            self.current()
            # The lock serializes cooperating binders. Also detect external
            # changes during settlement/UI validation before accepting reuse
            # or adding another binding; never silently replace a removed one.
            for row in self.plan['batches']:
                path = self.directory/f"batch-{identifier(row['batch_id'])}.json"
                if path in prior:
                    if _read(path)[1] != prior[path]:
                        raise ValueError('existing batch binding changed')
                elif os.path.lexists(path):
                    raise ValueError('batch binding appeared during validation')
            if not os.path.lexists(target):
                binding['bound'] = now
                write_once(target, binding)
            return copy.deepcopy(binding)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--directory', required=True)
    commands = parser.add_subparsers(dest='command', required=True)
    create = commands.add_parser('declare')
    create.add_argument('--batches', required=True, help='private JSON file containing complete batch list')
    bind = commands.add_parser('bind')
    bind.add_argument('--batch-id', required=True)
    bind.add_argument('--config', required=True)
    bind.add_argument('--job-id', required=True)
    attempt = commands.add_parser('register-attempt')
    attempt.add_argument('--batch-id', required=True)
    attempt.add_argument('--invocation', required=True)
    attempt.add_argument('--sha256', required=True)
    attempt.add_argument('--runner-directory', required=True)
    commands.add_parser('attempts', help='revalidate the complete pre-run attempt set')
    commands.add_parser('resolve', help='validate and freeze every declared actual binding')
    args = parser.parse_args()
    if args.command == 'declare':
        plan = declare(args.directory, _read(Path(args.batches))[0])
        print(json.dumps({'run_id': plan['run_id'], 'planned_sessions': plan['planned_sessions']}))
    elif args.command == 'register-attempt':
        result = RunManifest(args.directory).register_attempt(args.batch_id,
            args.invocation, args.sha256, args.runner_directory)
        print(json.dumps({'batch_id': result['batch_id'], 'invocation_id': result['invocation_id']}))
    elif args.command == 'attempts':
        result = RunManifest(args.directory).attempts()
        print(json.dumps({'attempts': len(result), 'run_terminal': False}))
    elif args.command == 'bind':
        result = RunManifest(args.directory).bind(args.batch_id, args.config, args.job_id)
        print(json.dumps({'run_id': result['run_id'], 'batch_id': result['batch_id'],
                          'action_id': result['action_id']}))
    else:
        result = RunManifest(args.directory).resolve()
        print(json.dumps({'run_id': result['run_id'], 'batches': len(result['batches']),
                          'planned_sessions': result['planned_sessions'], 'run_terminal': False}))


if __name__ == '__main__':
    main()
